
export const INVALIDATE_STORIES = "INVALIDATE_STORIES";
export const REFRESH_STORIES = "REFRESH_STORIES";
export const VIEW_STORY_DETAIL = "VIEW_STORY_DETAIL";
export const REFRESH_STORY_DETAIL = "REFRESH_STORY_DETAIL";