
export const INVALIDATE_STORIES = "INVALIDATE_STORIES";
export const REFRESH_STORIES = "REFRESH_STORIES";
export const VIEW_ITEM_DETAIL = "VIEW_ITEM_DETAIL";
export const REFRESH_ITEM_DETAIL = "REFRESH_ITEM_DETAIL";
export const PUSH_COMMENTS = "PUSH_COMMENTS";
export const INVALIDATE_ASKS = "INVALIDATE_ASKS";
export const REFRESH_ASKS = "REFRESH_ASKS";
export const INVALIDATE_SHOWS = "INVALIDATE_SHOWS";
export const REFRESH_SHOWS = "REFRESH_SHOWS";
export const INVALIDATE_LATEST = "INVALIDATE_LATEST";
export const REFRESH_LATEST = "REFRESH_LATEST";